[package]
name = "launcher"
version.workspace = true
edition.workspace = true

[dependencies]
converter = { path = "../converter/" }
shared = { path = "../shared/" }
bevy.workspace = true
serde_json.workspace = true
crossbeam-channel = "0.5.16"
tokio.workspace = true

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
