[package]
name = "converter"
version.workspace = true
edition.workspace = true

[dependencies]
mesh-tools.workspace = true
basis-universal.workspace = true
ddsfile.workspace = true
nom.workspace = true
rusqlite.workspace = true
rkyv.workspace = true
color-eyre.workspace = true
memmap2 = "0.9.11"
flate2   = "1.1.9"
crossbeam-channel  = "0.5.16"
